### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rainierpineda2** [CloudGenix/sdk-python#13]
Hello - I encountered this error when I installed the Python SDK API, I used pip install cloudgenix. The output is below.
Collecting cloudgenix
  Using cached https://files.pythonhosted.org/packages/65/8c/b2c8595b60c79bb1d238798fdf372e72928ebe574a6e362811eecd21c29d/cloudgenix-5.1.1b1.tar.gz
Collecting requests[security]>=2.18.4 (from cloudgenix)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests[security]>=2.18.4->cloudgenix)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 8.9MB/s 
Collecting cryptography>=1.3.4; extra == "security" (from requests[security]>=2.18.4->cloudgenix)
  Downloading https://files.pythonhosted.org/packages/c3/c1/cf8665c955c9393e9ff0872ba6cd3dc6f46ef915e94afcf6e0410508ca69/cryptography-2.6.1-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 7.8MB/s 
Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.18.4->cloudgenix)
  Downloading https://files.pythonhosted.org/packages/9d/6f/aea9f5559fb593da07ff34e67513bd62483b45715b4a5f5fae6a0a5792ea/cffi-1.12.2-cp27-cp27mu-manylinux1_x86_64.whl (413kB)
    100% |████████████████████████████████| 419kB 11.4MB/s 
Collecting six>=1.4.1 (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.18.4->cloudgenix)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "security"->requests[security]>=2.18.4->cloudgenix)
  Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rtRH5a/pycparser/setup.py", line 65, in <module>
        cmdclass={'install': install, 'sdist': sdist},
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2356, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rtRH5a/pycparser/
[u1163139@usdf23v0724 f5-to-netbox]$ pip freeze | grep cloudgenix
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
cloudgenix==5.1.1b1

It seems to have installed the module. Is that error ok to ignore?

**Comment by vivaciousvivek** [comment]
Hi @rainierpineda2,  
This is due to the python version error. You need **python >=3.6.x along with compatible pip** and use **pip3 install cloudgenix** instead of pip. 
Here may be 2 possibilities of this error:
1. If you are using old version Linux Distribution(For ex. **below Ubuntu 18.04**). So in this, if you install python3 without specifying the version(i.e >=3.6.x) then it installs a lower version of Python 3.6.x.
2. If you install the Python 3.6.x and your pip is not updated/compatible with this version.

So solutions for this:
1. Install a correct Linux distribution which can install default Python and pip version >= 3.6.x, when you install Python3. **(Recommended Approach)**
2. You can use any Linux distribution with the correct version of Python and pip 3.6.

Thanks

**Comment by ebob9** [comment]
I believe this is an issue with a specific version of setuptools and python 2.7 that was fixed. Please attempt upgrading setuptools via `sudo pip install setuptools --upgrade`, and try reinstalling.

**Comment by ebob9** [comment]
@rainierpineda2 Closing this thread - if you are still having issues, please let us know!
