### ISSUE TITLE
How to update the CloudGenix Python SDK 

### ISSUE THREAD

**Issue by moorets1** [CloudGenix/sdk-python#24]
How is the command to update the SDK

WARNING: CloudGenix Python SDK upgrade available. SDKs are typically deprecated 6 months after release of a new version.
        Latest Version: 5.5.1b2
        Current Version: 5.4.3b1
        For more info, see 'https://github.com/cloudgenix/sdk-python'. Additionally, this message can be suppressed by instantiating the API with API(update_check=False).

**Comment by dipeshah** [comment]
Hi @moorets1 

You could do that by executing : `pip install --upgrade cloudgenix`

Hope this helps!

**Comment by moorets1** [comment]
Here is the results

PS C:\CloudGenix_Python> pip install --upgrade cloudgenix
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: c:\users\moorets1\appdata\local\programs\python\python39\Include\UNKNOWN
sysconfig: c:\users\moorets1\appdata\local\programs\python\python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Requirement already satisfied: cloudgenix in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (5.4.3b1)
Collecting cloudgenix
  Downloading cloudgenix-5.5.1b2.tar.gz (75 kB)
     |████████████████████████████████| 75 kB 1.2 MB/s
Requirement already satisfied: requests[security]>=2.22.0 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from cloudgenix) (2.25.0)
Requirement already satisfied: websockets>=8.1 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from cloudgenix) (8.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from requests[security]>=2.22.0->cloudgenix) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from requests[security]>=2.22.0->cloudgenix) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from requests[security]>=2.22.0->cloudgenix) (1.26.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from requests[security]>=2.22.0->cloudgenix) (3.0.4)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from requests[security]>=2.22.0->cloudgenix) (3.3.1)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from requests[security]>=2.22.0->cloudgenix) (20.0.0)
Requirement already satisfied: cffi>=1.12 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from cryptography>=1.3.4->requests[security]>=2.22.0->cloudgenix) (1.14.4)
Requirement already satisfied: six>=1.4.1 in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from cryptography>=1.3.4->requests[security]>=2.22.0->cloudgenix) (1.15.0)
Requirement already satisfied: pycparser in c:\users\moorets1\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.12->cryptography>=1.3.4->requests[security]>=2.22.0->cloudgenix) (2.20)
Using legacy 'setup.py install' for cloudgenix, since package 'wheel' is not installed.
Installing collected packages: cloudgenix
  Attempting uninstall: cloudgenix
    Found existing installation: cloudgenix 5.4.3b1
    Uninstalling cloudgenix-5.4.3b1:
      Successfully uninstalled cloudgenix-5.4.3b1
   Running setup.py install for cloudgenix ... done
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: c:\users\moorets1\appdata\local\programs\python\python39\Include\UNKNOWN
sysconfig: c:\users\moorets1\appdata\local\programs\python\python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cloudgenix-config 1.3.0b3 requires cloudgenix<5.5.1b1,>=5.4.1b1, but you have cloudgenix 5.5.1b2 which is incompatible.
Successfully installed cloudgenix-5.5.1b2




Thank You,

Thomas Moore
Network Engineer
Air Products Inc.



“Do what is right, not what is easy nor what is popular.”

― Roy T. Bennett,


From: dipesh ***@***.***>
Sent: Tuesday, April 27, 2021 4:47 PM
To: CloudGenix/sdk-python ***@***.***>
Cc: Moore,Thomas S. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [CloudGenix/sdk-python] How to update the CloudGenix Python SDK (#24)


This email is from an external source. Please exercise caution in opening attachments or links.

Hi @moorets1<https://github.com/moorets1>

You could do that by executing : pip install --upgrade cloudgenix

Hope this helps!

**Comment by dipeshah** [comment]
@moorets1 

cloudgenix-config 1.3.0b3 does not support 5.5.1. Since cloudgenix-config package is tightly coupled with respestive SDK/api version as stated in the README/Caveats section, hence its better to upgrade cloudgenix-config too.
https://github.com/CloudGenix/cloudgenix_config/blob/master/README.md

Please upgrade to latest cloudgenix_config 1.4.0b3 which is compatible with 5.5.1b2.

**Comment by ktanushree** [comment]
@moorets1 closing this issue. If you have any questions, please feel free to reach out.
