### ISSUE TITLE
put attribute failure for bgpconfigs

### ISSUE THREAD

**Issue by adamashley** [CloudGenix/sdk-python#30]
My put-data seems to have all the required attributes listed in the comments in the code for this put however I am receiving "Input JSON does not have all required attributes".  The following is the request and the jd_detail for the response. 

PUT request:
resp = sdk.put.bgpconfigs(site_id=toSID, element_id=toEID, bgpconfig_id=toBGPconfigID, data=conf)

JD Detail for the response:
In [15]: jd_detailed(resp)
REQUEST: PUT /v2.2/api/tenants/XXXX/sites/XXXXXXXXXXXXX/elements/XXXXXXXXXXXXX/bgpconfigs/XXXXXXXXXXXXX
REQUEST HEADERS:
	User-Agent: python-requests/2.26.0 (CGX SDK v5.6.1b2)
	Accept-Encoding: gzip, deflate
	Accept: application/json
	Connection: keep-alive
	X-Auth-Token: <SENSITIVE - NOT SHOWN BY DEFAULT>
	Content-Type: application/json
	Cookie: AUTH_TOKEN="<SENSITIVE - NOT SHOWN BY DEFAULT>"
	Content-Length: 561
REQUEST BODY:
{
    "router_id": "X.X.X.X",
    "local_as_num": "XXXXX",
    "keepalive_time": 30,
    "hold_time": 90,
    "adv_interval": 1,
    "peer_retry_time": 120,
    "md5_secret": null,
    "multi_hop_limit": 1,
    "maximum_paths": 1,
    "admin_distance": 20,
    "graceful_restart": false,
    "stalepath_time": 120,
    "prefix_adv_type": "aggregate-manual",
    "prefixes_to_adv_to_wan": [
        "X.X.X.X",
        "X.X.X.X",
        "X.X.X.X", 
        "X.X.X.X",
        "X.X.X.X",
        "X.X.X.X",
        "X.X.X.X",
        "X.X.X.X",
    ],
    "prefix_adv_type_to_lan": "default",
    "peer_auth_type": "none"
}

RESPONSE: 400 Bad Request
RESPONSE HEADERS:
	Date: Thu, 28 Oct 2021 22:03:57 GMT
	Content-Length: 270
	Connection: keep-alive
	Server: nginx
RESPONSE DATA:
{
    "_etag": 0,
    "_content_length": "0",
    "_schema": 0,
    "_created_on_utc": 0,
    "_updated_on_utc": 0,
    "_status_code": "400",
    "_request_id": "XXXXXXXXXXXXXXXXXXXXXXXX",
    "_error": [
        {
            "code": "INVALID_JSON_INPUT",
            "message": "\"Input JSON does not have all required attributes.\""
        }
    ]
}

**Comment by ktanushree** [comment]
Hi! Your request payload for the PUT operation does not have key attributes like "id" and "_etag". Hence, the API endpoint is complaining about missing attributed.

The best way to determine the payload for a PUT operation would be to do a GET on the resource and use that payload for the PUT operation. 

eg:

resp = sdk.get.bgpconfigs(site_id=toSID, element_id=toEID, bgpconfig_id=toBGPconfigID)
if resp.cgx_status:
    data = resp.cgx_content
    # Make updates to data here 
    
    resp = sdk.put.bgpconfigs(site_id=toSID, element_id=toEID, bgpconfig_id=toBGPconfigID, data=data)
    
    
Please let me know if you still run into issues.
